### PR TITLE
Feat/newebpay payload for subscription creation

### PR DESCRIPTION
**Pull request by bcgodev**
#### What type of PR is this?
/kind feature
/kind api-change

#### What this PR does / why we need it:

To make s payment with `Newebpay`, apigateway needs to provide a `TradeInfo` to the client when it's creating a subscription.

The trade info will be provided in two different format depending on the scenarios, `recurring` subscription and `one_time` subscription.

For recurring subscriptions, the `TradeInfo` will include the following properties
```
Amt
ClientBackURL
Email
EmailModify
LoginType
MerchantOrderNo
NotifyURL
RespondType
ReturnURL
MerchantID
TimeStamp
Version
CREDITAGREEMENT
OrderComment
P3D
TokenTerm
```

For `one_time` subscription, they will be
```
Amt
ClientBackURL
Email
EmailModify
LoginType
MerchantOrderNo
NotifyURL
RespondType
ReturnURL
MerchantID
TimeStamp
Version
OrderComment
ItemDesc
```

For the feature to work, apigateway MUST be configured with the following properties to create a Newebpay Store:
```
CallbackDomain
CallbackProtocol
ClientBackPath
ID
IsAbleToModifyEmail
LoginType
NotifyProtocol
NotifyDomain
NotifyPath
Is3DSecure
RespondType
ReturnPath
Version
```

I took the liberty to design the structure of `TradeInfo`.

1. `NotifyUrl`: since Newebpay will add necessary payload in a POST request to Notify URL, `NotifyURL` will simply be  in this format, `https://domain/notify-payment`
2. `ReturnURL and `ClientBackURL`: I add some parameters to provide info for client-side conveniently.

For `one_time` subscription, `ReturnURL` includes
```
amount
code
memberFirebaseId
orderNumber
postId
postSlug
postTitle
purchasedAtUnixTime
returnPath
```
`ReturnPath` is designed so that client-side knows which path it may direct user to after the purchase is complete. `code` is just the `frequency` of the subscription with a different name, but it's the actual property in the merchandise of `Israfel`

For recurring subscription, `ReturnURL` is the almost the same with fewer properties:
```
amount
code
memberFirebaseId
orderNumber
purchasedAtUnixTime
returnPath
```

#### Which issue(s) this PR fixes:
NONE

#### Special notes for your reviewer:

There are several elements unknown to the gateway, and they are listed below. Please help provide them. Thanks.

@ItchyWang Can you please provide the Store ID a.k.a. `MerchandiseID` in the Newebpay document

@kwhsiung Can you please provide the `ClientBackPath`, and `ReturnPath`. They are supposed to be absolute path like `/complete-purchase`.

`CallbackDomain` and `CallbackProtocol` are also needed, the URLs will be composited with them and the above paths.

I suppose domain and protocol are depending to the stages? Please correct me if I am wrong. Thanks.

@nickhsine Can you please provide `NotifyPath`, `NotifyProtocol`, and `NotifyDomain`. Thanks.

Here are some examples, I would love to know your feedback. It would be much appreciated.

 - `NotifyURL`: `https://domain/notify-payment`
 - `ReturnURL`: `https://domain/complete-purchase?amount=8888&code=one_time&memberFirebaseId=memberid&orderNumber=ordernumber&postId=postid&postSlug=postslug&postTitle=posttitle&purchasedAtUnixTime=111&returnPath=%2Fstory%2Fabc`
 - `ClientBackPath`: `https://domain/cancel-purchase?amount=8888&code=one_time&memberFirebaseId=memberid&orderNumber=ordernumber&postId=postid&postSlug=postslug&postTitle=posttitle&purchasedAtUnixTime=111&returnPath=%2Fstory%2Fabc`
 - `Recurring Subscription Newebpay Payload`: `Amt=8888&CREDITAGREEMENT=1&ClientBackURL=https%3A%2F%2Fclientbackdomain%2Fclientback%3Famount%3D8888%26code%3Dyearly%26memberFirebaseId%3Dmemberid%26orderNumber%3Dordernumber%26purchasedAtUnixTime%3D111%26returnPath%3D%252Fstory%252Fabc&Email=email%40mail.com&EmailModify=1&LoginType=0&MerchantID=store+id&MerchantOrderNo=ordernumber&NotifyURL=https%3A%2F%2Fnotifydomain%2Fnotify&OrderComment=comment&P3D=1&RespondType=JSON&ReturnURL=https%3A%2F%2Fclientbackdomain%2Fhttp%3A%2F%2Freturnpath%3Famount%3D8888%26code%3Dyearly%26memberFirebaseId%3Dmemberid%26orderNumber%3Dordernumber%26purchasedAtUnixTime%3D111%26returnPath%3D%252Fstory%252Fabc&TimeStamp=123&TokenTerm=firebaseID&Version=1.6`

There are other questions for the `TradeInfo`:
1. What should `OrderComment` be?
2. What should `ItemDescription` be?
3. Can `one_time` subscription omit `OrderComment`

Your suggestions are appreciated. Thanks in advance.

c.c. To keep @liyibass in the loop

#### Does this PR introduce a user-facing change?
```release-note
1. returnToPath is added to the input of subscription creation mutation for TradeInfo
2. postSlug and postTitle are added to the input of subscription creation mutation for TradeInfo
```

#### Additional documentation e.g., usage docs, etc.:
```
- Usage: Unit tests are added, and example may be found in them. https://github.com/mirror-media/apigateway/pull/45/files#diff-661db55381103598980560a31121fc375ebdb0ddef78ae670c4f22286c345dab
- Doc: one_time payment  https://github.com/mirror-media/apigateway/files/6866874/Newebpay_MPG._MPG_1.1.0.pdf
- Doc: recurring payment https://github.com/mirror-media/apigateway/files/6866877/Newebpay_.V1.0.2.pdf
```

### CODE REVIEW

**Comment by nickhsine** [comment]
## Production setup
### monthly subscription:
- `NotifyPath`: `/newebpay/period/monthly`
- `NotifyProtocol`: `https`
- `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

### yearly subscription:
- `NotifyPath`: `/newebpay/period/yearly`
- `NotifyProtocol`: `https`
- `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

### one_time subscription:
- `NotifyPath`: `/newebpay/one_time`
- `NotifyProtocol`: `https`
- `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

## Staging
`NotifyPath` and `NotifyProtocol` are the same as production setup,
only `NotifyDomain` will be changed to `staging-payment-webhooks.mirrormedia.mg`

## Dev
`NotifyPath` and `NotifyProtocol` are the same as production setup,
only `NotifyDomain` will be changed to `dev-payment-webhooks.mirrormedia.mg`

Btw, could we change `NotifyDomain` to `NotifyHostname`, since the `domain` will be `mirrormedia.mg`.

**Comment by kwhsiung** [comment]
> @kwhsiung Can you please provide the ClientBackPath, and ReturnPath. They are supposed to be absolute path like /complete-purchase.

`ClientBackPath`: `https://domain/subscribe/cancel-purchase`
`ReturnPath`: `https://domain/subscribe/complete-purchase`

**Comment by bcgodev** [comment]
> ### monthly subscription:
> 
>     * `NotifyPath`: `/newebpay/period/monthly`
> 
>     * `NotifyProtocol`: `https`
> 
>     * `NotifyDomain`: `payment-webhooks.mirrormedia.mg`
> 
> 
> ### yearly subscription:
> 
>     * `NotifyPath`: `/newebpay/period/yearly`
> 
>     * `NotifyProtocol`: `https`
> 
>     * `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

@nickhsine Can we to use the frequency in the url query instead of the path? I can imagine a single entry point for payment webhook would make the workflow cleaner?

**Comment by ItchyWang** [comment]
MerchandiseID：MS38267013 (鏡週刊Mirror Media)

**Comment by nickhsine** [comment]
> @nickhsine Can we use the frequency in the url query instead of the path? I can imagine a single entry point for payment webhook would make the workflow cleaner?

How about providing the URLs you want to me?
I could change payment-webhooks-publishers endpoints.

**Comment by bcgodev** [comment]
> > @nickhsine Can we use the frequency in the url query instead of the path? I can imagine a single entry point for payment webhook would make the workflow cleaner?
> 
> How about providing the URLs you want to me?
> I could change payment-webhooks-publishers endpoints.

@nickhsine How about `/newebpay` with a query `code`, where `code` is the merchandise code in `Israfel`? Like `/newebpay?code=one_time`. Will it do for you?

**Comment by bcgodev** [comment]
@ItchyWang @kwhsiung Please kindly be reminded that subscription's description cannot contain unsafe characters, which are [:/?#[]@!$&'()*+,;=<>%{}|\^"` and line breaker](https://github.com/mirror-media/apigateway/pull/45/files#diff-3098f334f8cdfd44bfda50dd7c9ecc0f916dff8ede50ecf6f83b24a29a33b105)

May I have an instruction what are recurring payment's `OrderComment` and `one_time` payment's `ItemDescription`? Is it appropriate to use subscription's description for both of them?

One more question. Is it OK that I don't include `OrderComment` for `one_time` subscription?

**Comment by nickhsine** [comment]
( Btw, could we change `NotifyDomain` to `NotifyHostname`? Since the `domain` will be `mirrormedia.mg`. )

## Production setup
### monthly subscription:
- `NotifyPath`: `/newebpay?frequency=monthly`
- `NotifyProtocol`: `https`
- `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

### yearly subscription:
- `NotifyPath`: `/newebpay?frequency=yearly`
- `NotifyProtocol`: `https`
- `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

### one_time subscription:
- `NotifyPath`: `/newebpay?frequency=one_time`
- `NotifyProtocol`: `https`
- `NotifyDomain`: `payment-webhooks.mirrormedia.mg`

## Staging
`NotifyPath` and `NotifyProtocol` are the same as production setup,
only `NotifyDomain` will be changed to `staging-payment-webhooks.mirrormedia.mg`

## Dev
`NotifyPath` and `NotifyProtocol` are the same as production setup,
only `NotifyDomain` will be changed to `dev-payment-webhooks.mirrormedia.mg`

**Comment by bcgodev** [comment]
@nickhsine Thanks for providing the detail.

Though the domain name here is actual a sub-domain, which is just another level of domain.
However in [RFC3987](https://datatracker.ietf.org/doc/html/rfc3986#page-18), it's called `host`.

I'll rename it to `Host`. Thanks for pointing that out! Great catch.

Another question, since in Israfel the merchandise is using `code` as its uid. Could we use `code` instead of `frequency`?

**Comment by nickhsine** [comment]
> @nickhsine Thanks for providing the detail.
> 
> Though the domain name here is actual a sub-domain, which is just another level of domain.
> However in [RFC3987](https://datatracker.ietf.org/doc/html/rfc3986#page-18), it's called `host`.
> 
> I'll rename it to `Host`. Thanks for pointing that out! Great catch.
> 
> Another question, since in Israfel the merchandise is using `code` as its uid. Could we use `code` instead of `frequency`?

Will the values of `code` be `one_time`, `monthly` and `yearly`? 
87

**Comment by bcgodev** [comment]
> Will the values of `code` be `one_time`, `monthly` and `yearly`?
Yes. They will, and they have to.

**Comment by bcgodev** [comment]
@nickhsine The PR prolong for quite some time. Is there anything missing for the functionality?

**Comment by nickhsine** [comment]
> @nickhsine The PR prolongs for quite some time. Is there anything missing for the functionality?

Sorry for late reply.
This suggestion looks good to me.
I have already make the [PR](https://github.com/mirror-media/payment-webhooks/pull/9) to adopt your solutions.

**Pull request merged**
